--- ../pgbouncer/Makefile	2022-03-23 10:54:35.000000000 +0100
+++ ./Makefile	2022-03-24 16:02:42.000000000 +0100
@@ -21,6 +21,9 @@
 	src/server.c \
 	src/stats.c \
 	src/system.c \
+	src/pycall.c \
+	src/route_connection.c \
+	src/rewrite_query.c \
 	src/takeover.c \
 	src/util.c \
 	src/varcache.c \
@@ -47,6 +50,9 @@
 	include/server.h \
 	include/stats.h \
 	include/system.h \
+	include/pycall.h \
+	include/route_connection.h \
+	include/rewrite_query.h \
 	include/takeover.h \
 	include/util.h \
 	include/varcache.h \
@@ -59,19 +65,20 @@
 	include/common/unicode_norm.h \
 	include/common/unicode_norm_table.h

-pgbouncer_CPPFLAGS = -Iinclude $(CARES_CFLAGS) $(LIBEVENT_CFLAGS) $(TLS_CPPFLAGS)
+python_CPPFLAGS = -I/usr/include/python3.8 -I/usr/include/python3.8
+pgbouncer_CPPFLAGS = -Iinclude $(CARES_CFLAGS) $(LIBEVENT_CFLAGS) $(TLS_CPPFLAGS) $(python_CPPFLAGS)

 # include libusual sources directly
 AM_FEATURES = libusual
 pgbouncer_EMBED_LIBUSUAL = 1

 # docs to install as-is
-dist_doc_DATA = README.md NEWS.md etc/pgbouncer.ini etc/userlist.txt
+dist_doc_DATA = README.md etc/pgbouncer.ini etc/userlist.txt

 DISTCLEANFILES = config.mak config.status lib/usual/config.h config.log

 DIST_SUBDIRS = doc test
-dist_man_MANS = doc/pgbouncer.1 doc/pgbouncer.5
+dist_man_MANS =

 # files in tgz
 EXTRA_DIST = AUTHORS COPYRIGHT Makefile config.mak.in config.sub config.guess \
@@ -92,8 +99,9 @@
 		lib/README lib/COPYRIGHT \
 		lib/find_modules.sh )))

+python_LDFLAGS = -lpthread -ldl -lutil -lm -lpython3.8 -Xlinker -export-dynamic
 pgbouncer_LDFLAGS := $(TLS_LDFLAGS)
-pgbouncer_LDADD := $(CARES_LIBS) $(LIBEVENT_LIBS) $(TLS_LIBS) $(LIBS)
+pgbouncer_LDADD := $(CARES_LIBS) $(LIBEVENT_LIBS) $(TLS_LIBS) $(LIBS) $(python_LDFLAGS)
 LIBS :=

 #

 
